fixing flow sensor flow rate calibration issue
pcdshub/lcls-plc-tmo-optics pull request #37
Opened 2023-09-13 23:21 UTC by tongju12

## Description
MR3K4 flow sensor GUI reading was wrong due to the wrong calibration from raw bit to flow rate. It showed 15 lpm while ME said the real flow rate should be around 2 lpm.

Jing and I checked the datasheet of EL3054 and recalibrate from the raw bit to match the flow capacity from the flow sensor DPM. After that, it shows 1.8 lpm which makes sense. The old calibration was wrong.
## Motivation and Context

The reading of flow sensor is not correct according to the limit of flow sensor capacity.
Here is the old FB : https://github.com/pcdshub/lcls-twincat-general/pull/82
Recalibrate the formula by the datasheet and manually calibrate first to get reasonable value.

https://jira.slac.stanford.edu/browse/ECS-3783
## How Has This Been Tested?

After I log in with the new FB, the current flow sensor reading of MR3K4 is 1.8 lpm and consistent with ME estimation 2lpm.

## Where Has This Been Documented?

https://jira.slac.stanford.edu/browse/ECS-3783)

## Screenshots (if appropriate):

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2023-09-13 23:35 UTC, tongju12 commented
I just run pre-commit run --all-files to fix those errors.

2023-09-14 00:13 UTC, ZLLentz reviewed
I'm kind of mostly confused here, I don't understand the new FB

2023-09-14 00:13 UTC, ZLLentz commented on lcls-plc-tmo-optics/tmo_optics/POUs/FB_AnalogInput1.TcPOU
> +    ratio: REAL;
this should not be an input parameter

2023-09-14 00:13 UTC, ZLLentz commented on lcls-plc-tmo-optics/tmo_optics/POUs/FB_AnalogInput1.TcPOU
> +   rC := 16.0*ratio + 4.0; // transfer the current mA base on raw bit reading
What exactly is going on here? What are these magic numbers?

2023-09-14 00:13 UTC, ZLLentz commented on lcls-plc-tmo-optics/tmo_optics/POUs/FB_AnalogInput1.TcPOU
> +   ]]></ST>
After reading this, it's not clear to me why the original FB couldn't have been used (just changing the arguments)

2023-09-14 19:27 UTC, ZLLentz requested changes
In the original FB the math basically just maps the output range of the sensor to the bit range in a very straightforward way. This FB seems to cannibalize the original in ways that seem unnecessary.

I don't think this is the right solution to the problem, unless there's something I don't understand about this sensor that makes it special- in which case, this should be a completely new FB instead of trying to reuse the guts of FB_AnalogInput

Does FB_AnalogInput with the following inputs not produce the right output?

- iTermBits := 15
- fTermMax := 5
- fTermMin := 0

2023-09-14 21:45 UTC, tongju12 commented on lcls-plc-tmo-optics/TLR_BI_01026916.TCLRS
remove them already

2023-09-14 21:45 UTC, tongju12 commented on lcls-plc-tmo-optics/TLR_BI_01026916.tclrq
remove it

2023-09-14 21:47 UTC, tongju12 commented
Remove the new FB, keep the old one.  Change the iTermBits from 12 to 15 and get reasonable output as 1.85 lpm.

2023-09-14 23:48 UTC, ZLLentz approved these changes

2023-09-15 16:41 UTC, merged

2023-09-25 22:15 UTC, nrwslac commented
Where did we get the 15 bits from? The documentation I see for the EL3054 says 12 bits. @tongju12

2023-09-25 22:59 UTC, ZLLentz commented
The EL3054 has a 12 bit resolution, but packs the data into a 16-bit unsigned integer, using only the positive side. This is in the datasheet as `Resolution	12 bit (16 bit presentation incl. sign)` The 3 least-significant bits are essentially useless noise but the output still needs to be scaled to 15 bits.

2023-09-25 23:37 UTC, nrwslac commented
I see, I guess this is a result of needing to represent the value using typical data types. The 12 bit must be the actual hardware bits available.

2023-09-25 23:43 UTC, ZLLentz commented
I think you're right- this is one of the choices you can make when you're packing a 12 bit integer into a 16 bit space. (It's not the choice that I would have made, but I'm sure there were good reasons for it)

2023-09-25 23:45 UTC, klauer commented
Ref: https://control.com/forums/threads/12-bit-ad-value-converted-to-16-bit-holding-register.6707/

2023-09-25 23:50 UTC, nrwslac commented
Interesting, never actually considered this kind of problem before.